import 'package:restaurants/features/home/domain/entities/restaurant_entity.dart';

List<RestaurantEntity> restaurantEntityDemo = [RestaurantEntity(
    id: '1',
    name: 'Demo Restaurant',
    description: 'staurant description.',
    imageUrl: null,
    rating: '4.5',
    address: '123 Demo Street',
    phone: '123-456-7890',
    category: 'Demo Category',
    openTime: '10:00 AM',
    closeTime: '10:00 PM',
    deliveryFee: 'Free',
  ),RestaurantEntity(
    id: '1',
    name: 'Demo Restaurant',
    description: 'staurant description.',
    imageUrl: null,
    rating: '4.5',
    address: '123 Demo Street',
    phone: '123-456-7890',
    category: 'Demo Category',
    openTime: '10:00 AM',
    closeTime: '10:00 PM',
    deliveryFee: 'Free',
  ),RestaurantEntity(
    id: '1',
    name: 'Demo Restaurant',
    description: 'staurant description.',
    imageUrl: null,
    rating: '4.5',
    address: '123 Demo Street',
    phone: '123-456-7890',
    category: 'Demo Category',
    openTime: '10:00 AM',
    closeTime: '10:00 PM',
    deliveryFee: 'Free',
  ),RestaurantEntity(
    id: '1',
    name: 'Demo Restaurant',
    description: 'staurant description.',
    imageUrl: null,
    rating: '4.5',
    address: '123 Demo Street',
    phone: '123-456-7890',
    category: 'Demo Category',
    openTime: '10:00 AM',
    closeTime: '10:00 PM',
    deliveryFee: 'Free',
  ),RestaurantEntity(
    id: '1',
    name: 'Demo Restaurant',
    description: 'staurant description.',
    imageUrl: null,
    rating: '4.5',
    address: '123 Demo Street',
    phone: '123-456-7890',
    category: 'Demo Category',
    openTime: '10:00 AM',
    closeTime: '10:00 PM',
    deliveryFee: 'Free',
  ),RestaurantEntity(
    id: '1',
    name: 'Demo Restaurant',
    description: 'staurant description.',
    imageUrl: null,
    rating: '4.5',
    address: '123 Demo Street',
    phone: '123-456-7890',
    category: 'Demo Category',
    openTime: '10:00 AM',
    closeTime: '10:00 PM',
    deliveryFee: 'Free',
  )];
